# Generated by Django 4.2.5 on 2023-09-14 04:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactapp',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
        ),
    ]
